version: "3.8"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "task-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB="${DB_DB}"
      - POSTGRES_USER="${DB_USERNAME}"
      - POSTGRES_PASSWORD="${DB_PASSWORD}"
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data
  
  api:
    build: .
    container_name: "task-manager-api"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - fullstack
  

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge